# Generated by Django 3.2 on 2021-04-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='device_price',
        ),
    ]
