# Generated by Django 3.2 on 2021-04-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210412_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='device_image',
            field=models.ImageField(blank=True, null=True, upload_to='crud/'),
        ),
    ]
