# Generated by Django 3.2 on 2021-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_crud_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='device_model',
            field=models.CharField(default='ABXCDN', max_length=100),
        ),
    ]
