# Generated by Django 3.2 on 2021-04-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20210412_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='device_image',
        ),
    ]
