# Generated by Django 3.2 on 2021-04-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='service',
        ),
    ]
